### ISSUE TITLE
Nothing actually runs after install

### ISSUE THREAD

**Issue by shanecasey** [htpcBeginner/AtoMiC-ToolKit#112]
New to Atomic and haven't managed to get anything to actually install yet. Install process runs fine but the programs don't actually run. I've tried with nzbget, nzbhydra and lazy librarian but it's always the same.

If I go to the right folder in /opt/ everything seems to be there but if I try and run anything I get the message that the service is not installed.

The only error I've spotted in installs seems to be a red error message:

> ...Autostart configuring ... 
> Unknown startup type.

When I go to check access details, Atomic says:

> No boot script found Try reinstalling...

under status.

Any ideas? I'm running Linux Mint 17 if that helps

**Comment by TommyE123** [comment]
Hi Shane,

Firstly thanks for logging an issue. 
If people dont tell me things are broken, unless i stumble across the issue myself I won't notice!

You have uncovered an issue that was previously reported a few weeks back however I think I may have a fix for this. Can you please update the toolkit (via the maintance menu) and give it another try and let me know the results?

Also i'd suggest you remove any applications you tried to install and then reinstall them so you get a nice clean start. :-)

**Comment by mgiljum** [comment]
I ran the latest version against a clean install of linux mint and the three applications mentioned installed without any major issues.

**Comment by shanecasey** [comment]
Amazing, that's fixed it! It worked a treat with lazy librarian and nzbget (although it broke unrar on my existing manual sabnzbd install). 

Nzbhydra seems to have installed and it says it's running when I run the access details but there's nothing at localhost:5075. Might be a different issue though.

Thanks for your work on this. Great tool for a Linux noob like myself

**Comment by TommyE123** [comment]
Great news!
I'm glad lazy librarian and nzbget are now working for you.

So what happened with the unrar and Sabnzbd? It should have installed the very latest version. I'm guessing you had it previously installed in another location?

i'll take a look at Nzbhydra and check there's no dependencies being missed from being installed that are required on older versions of Linux.
I'd also suggest you just try rebooting Linux just to double check it doesn't kick it into life!

Tom

**Comment by shanecasey** [comment]
I'd manually installed sabnzbd with the installer from https://sabnzbd.org/downloads a while back. After I updated and ran the nzbget installer, sabnzbd had an error at the top
>  No UNRAR program found, unpacking RAR files is not possible

I could try reinstalling it but tbh might just stick with nzbget through atomic now.

I'll try rebooting tonight and let you know if hydra works

**Comment by shanecasey** [comment]
Reboot didn't work. Neither did updating Atomic and uninstalling/reinstalling Hydra. Seems to be just an issue with Hydra though as anything else I've tried (like htpcmanager) are working fine.

Here's the screen when I check access details, if that helps. 
![screen shot 2017-03-20 at 11 22 02](https://cloud.githubusercontent.com/assets/1871492/24098032/77b66516-0d60-11e7-9a09-0096e958726f.png)

**Comment by TommyE123** [comment]
Great idea posting the screenshot!
I can see a problem at the top of this suggesting it hasn't installed correctly as it can't find the nzbhydra.cfg file. It also highlights we have a problem with the "Checking NZBHydra status" as it obviously shouldn't say its running and accessible! 
I'm not going to be able to look at this until later this evening. 
However I have a good guess what this could be! NZBHydra uses HTTPS for its github location and if you don't have "apt-transport-https" installed I don't think you can pull anything down from there. 
I've already pushed a fix for this issue but not up to the master branch yet.

For now please could you do the following steps?
1. via the "Maintenance Menu" in the toolkit select "Update ToolKit" to make sure you have the latest version.

2. via the "Maintenance Menu" select "Update Linux". From the screenshot above you have 53 not upgraded packages and a few old mono libs hanging around.

3. Run the following command at a terminal prompt to install the common Toolkit required packages without quotes "**sudo apt-get install apt-transport-https build-essential checkinstall curl dnsutils git mediainfo mediainfo-gui p7zip-full par2 sed software-properties-common sqlite3 tar unzip wget zip -y**"

4. Remove (if it will let you) and reinstall NZBhydra.

Let me know how you get on. :-)

Tom

**Comment by shanecasey** [comment]
All steps done and updated, and ran updates in apt-get too but still no luck.

Still saying it's running but like you spotted the nzbhydra.cfg file/directory doesn't exist

![screen shot 2017-03-20 at 16 22 20](https://cloud.githubusercontent.com/assets/1871492/24109725/74f1d60c-0d89-11e7-9d0a-ea57cf1f40a9.png)

**Comment by TommyE123** [comment]
Wow. 
I'd have put money on that working.. ok let me have a look later. Its bugging me now!
Did you spot any errors whilst it tries to install?
I wasn't thinking earlier and apt-transport-https is probably nothing to do with it as this is a git location and that's only needed for adding https repositories I think.

**Comment by TommyE123** [comment]
Right! pretty sure I've found the issue :-) I'm assuming your still running Linux Mint 17? NZBHydra requires at least python version 2.7.9. Could you run the following command and just confirm what it says (i'm predicting 2.7.6!)?
**sudo service nzbhydra restart**
and 
**python --version**

If this is the case can you try the following?
**sudo add-apt-repository ppa:jonathonf/python-2.7**
**sudo apt-get update
sudo apt-get dist-upgrade**
**python --version** (check it says 2.7.13)
**sudo service nzbhydra restart**

I've just done this on a vm of Linux Mint 17.3 and NZBHydra now appears to be working. However i'm certainly not a python expert and although this was ok for me I would air some caution.

I know this sounds a bit drastic but is there any reason why you wouldn't consider updating to the latest version of Linux mint 18.1 in the future?

**Comment by shanecasey** [comment]
Success! Nailed it. Was 2.7.6 and it's 2.7.13 now.

Sorry for taking so much of your time. This is my first Linux box so haven't upgraded to 18 simply because it's stable and running well as my HTPC. I'll definitely do some reading up though... obviously there was reason to upgrade that I wasn't even aware of.

Thanks again.

**Comment by TommyE123** [comment]
No problem at all. Glad I could help. I've raised 2 issues to try and address both the python version and better access details information for future. If you get any further problems please do continue to log issues :-)
Tom
